"""Add ecommerce loyalty promo rfid oms tables

Revision ID: 8ffa21c359ed
Revises: e216122cf21f
Create Date: 2025-11-26 23:35:33.219506

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ffa21c359ed'
down_revision = 'e216122cf21f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('uso_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tienda_id'), 'api_keys', ['tienda_id'], unique=False)
    op.create_table('integraciones_ecommerce',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('plataforma', sa.Enum('SHOPIFY', 'WOOCOMMERCE', 'TIENDANUBE', 'CUSTOM', name='plataformaecommerce'), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_test', sa.DateTime(), nullable=True),
    sa.Column('connection_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_sync_products', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_stock', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_orders', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhooks_configured', sa.Boolean(), nullable=False),
    sa.Column('webhook_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integraciones_ecommerce_tienda_id'), 'integraciones_ecommerce', ['tienda_id'], unique=False)
    op.create_table('loyalty_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('tasa_acumulacion', sa.Float(), nullable=False),
    sa.Column('valor_punto_pesos', sa.Float(), nullable=False),
    sa.Column('puntos_minimos_canje', sa.Integer(), nullable=False),
    sa.Column('puntos_expiran', sa.Boolean(), nullable=False),
    sa.Column('dias_expiracion_puntos', sa.Integer(), nullable=True),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('puntos_bienvenida', sa.Integer(), nullable=False),
    sa.Column('puntos_cumpleaños', sa.Integer(), nullable=False),
    sa.Column('puntos_referido', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tienda_id')
    )
    op.create_table('promociones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codigo_promocional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sa.Enum('DESCUENTO_PORCENTAJE', 'DESCUENTO_MONTO', 'COMBO_2X1', 'COMBO_3X2', 'COMBO_NXM', 'TIERED_PRICING', 'BUNDLE', 'REGALO', 'ENVIO_GRATIS', 'CUPON', name='tipopromo'), nullable=False),
    sa.Column('reglas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('productos_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('colecciones_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categorias_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('dias_semana', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hora_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hora_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usos_maximos', sa.Integer(), nullable=True),
    sa.Column('usos_maximos_por_cliente', sa.Integer(), nullable=True),
    sa.Column('usos_actuales', sa.Integer(), nullable=False),
    sa.Column('monto_minimo_compra', sa.Float(), nullable=True),
    sa.Column('cantidad_minima_items', sa.Integer(), nullable=True),
    sa.Column('canales_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formas_pago_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('es_acumulable', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('badge_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('badge_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promociones_codigo_promocional'), 'promociones', ['codigo_promocional'], unique=True)
    op.create_index(op.f('ix_promociones_tienda_id'), 'promociones', ['tienda_id'], unique=False)
    op.create_table('shipping_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provincias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('codigos_postales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('costo_standard', sa.Float(), nullable=False),
    sa.Column('costo_express', sa.Float(), nullable=False),
    sa.Column('costo_same_day', sa.Float(), nullable=False),
    sa.Column('dias_standard', sa.Integer(), nullable=False),
    sa.Column('dias_express', sa.Integer(), nullable=False),
    sa.Column('dias_same_day', sa.Integer(), nullable=False),
    sa.Column('umbral_envio_gratis', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('puntos_disponibles', sa.Integer(), nullable=False),
    sa.Column('puntos_lifetime', sa.Integer(), nullable=False),
    sa.Column('valor_punto', sa.Float(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier_desde', sa.DateTime(), nullable=True),
    sa.Column('gift_cards_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_wallets_cliente_id'), 'customer_wallets', ['cliente_id'], unique=True)
    op.create_index(op.f('ix_customer_wallets_tienda_id'), 'customer_wallets', ['tienda_id'], unique=False)
    op.create_table('gift_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('monto_original', sa.Float(), nullable=False),
    sa.Column('monto_actual', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.Column('canal_compra', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venta_origen_id', sa.Uuid(), nullable=True),
    sa.Column('es_regalo', sa.Boolean(), nullable=False),
    sa.Column('mensaje_regalo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destinatario_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['venta_origen_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_cards_codigo'), 'gift_cards', ['codigo'], unique=True)
    op.create_table('location_capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('puede_despachar', sa.Boolean(), nullable=False),
    sa.Column('puede_recibir_pickup', sa.Boolean(), nullable=False),
    sa.Column('horario_despacho', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soporta_same_day', sa.Boolean(), nullable=False),
    sa.Column('soporta_express', sa.Boolean(), nullable=False),
    sa.Column('soporta_standard', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('costo_picking', sa.Float(), nullable=False),
    sa.Column('costo_packing', sa.Float(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('ordenes_omnicanal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('numero_orden', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plataforma', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuentos', sa.Float(), nullable=False),
    sa.Column('envio', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fulfillment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fulfillment_location_id', sa.Uuid(), nullable=True),
    sa.Column('routing_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['fulfillment_location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_omnicanal_canal'), 'ordenes_omnicanal', ['canal'], unique=False)
    op.create_index(op.f('ix_ordenes_omnicanal_fulfillment_status'), 'ordenes_omnicanal', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_ordenes_omnicanal_numero_orden'), 'ordenes_omnicanal', ['numero_orden'], unique=True)
    op.create_index(op.f('ix_ordenes_omnicanal_tienda_id'), 'ordenes_omnicanal', ['tienda_id'], unique=False)
    op.create_table('promocion_usos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('promocion_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('descuento_aplicado', sa.Float(), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promociones.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocion_usos_cliente_id'), 'promocion_usos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_promocion_usos_promocion_id'), 'promocion_usos', ['promocion_id'], unique=False)
    op.create_table('rfid_readers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('reader_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fabricante', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('potencia_transmision', sa.Integer(), nullable=True),
    sa.Column('frecuencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('puerto', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_readers_reader_id'), 'rfid_readers', ['reader_id'], unique=True)
    op.create_table('rfid_scan_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('reader_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reader_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags_escaneados', sa.Integer(), nullable=False),
    sa.Column('tags_unicos', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integracion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('items_procesados', sa.Integer(), nullable=False),
    sa.Column('items_exitosos', sa.Integer(), nullable=False),
    sa.Column('items_fallidos', sa.Integer(), nullable=False),
    sa.Column('errores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('sync_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['integracion_id'], ['integraciones_ecommerce.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_integracion_id'), 'sync_logs', ['integracion_id'], unique=False)
    op.create_table('gift_card_usos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gift_card_id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('monto_usado', sa.Float(), nullable=False),
    sa.Column('monto_restante', sa.Float(), nullable=False),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_card_usos_gift_card_id'), 'gift_card_usos', ['gift_card_id'], unique=False)
    op.create_table('orden_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('orden_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('allocated_from_location', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_from_location'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_omnicanal.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integracion_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('external_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('sync_errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integracion_id'], ['integraciones_ecommerce.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_mappings_external_product_id'), 'product_mappings', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_product_mappings_external_variant_id'), 'product_mappings', ['external_variant_id'], unique=False)
    op.create_index(op.f('ix_product_mappings_integracion_id'), 'product_mappings', ['integracion_id'], unique=False)
    op.create_index(op.f('ix_product_mappings_product_id'), 'product_mappings', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_mappings_variant_id'), 'product_mappings', ['variant_id'], unique=False)
    op.create_table('rfid_inventory_discrepancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_sistema', sa.Integer(), nullable=False),
    sa.Column('cantidad_fisica', sa.Integer(), nullable=False),
    sa.Column('diferencia', sa.Integer(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['rfid_scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_scan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('epc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('detectado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('antenna_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['rfid_scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_scan_items_epc'), 'rfid_scan_items', ['epc'], unique=False)
    op.create_index(op.f('ix_rfid_scan_items_session_id'), 'rfid_scan_items', ['session_id'], unique=False)
    op.create_table('rfid_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('epc', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultima_lectura', sa.DateTime(), nullable=True),
    sa.Column('ultimo_lector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_encodificacion', sa.DateTime(), nullable=False),
    sa.Column('lote_fabricacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tag_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_tags_epc'), 'rfid_tags', ['epc'], unique=True)
    op.create_index(op.f('ix_rfid_tags_tienda_id'), 'rfid_tags', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_rfid_tags_variant_id'), 'rfid_tags', ['variant_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('ACUMULACION_COMPRA', 'CANJE_PUNTOS', 'REGALO', 'EXPIRACION', 'AJUSTE_MANUAL', 'DEVOLUCION', name='tipotransaccionwallet'), nullable=False),
    sa.Column('puntos_delta', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['customer_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_rfid_tags_variant_id'), table_name='rfid_tags')
    op.drop_index(op.f('ix_rfid_tags_tienda_id'), table_name='rfid_tags')
    op.drop_index(op.f('ix_rfid_tags_epc'), table_name='rfid_tags')
    op.drop_table('rfid_tags')
    op.drop_index(op.f('ix_rfid_scan_items_session_id'), table_name='rfid_scan_items')
    op.drop_index(op.f('ix_rfid_scan_items_epc'), table_name='rfid_scan_items')
    op.drop_table('rfid_scan_items')
    op.drop_table('rfid_inventory_discrepancies')
    op.drop_index(op.f('ix_product_mappings_variant_id'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_product_id'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_integracion_id'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_external_variant_id'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_external_product_id'), table_name='product_mappings')
    op.drop_table('product_mappings')
    op.drop_table('orden_items')
    op.drop_index(op.f('ix_gift_card_usos_gift_card_id'), table_name='gift_card_usos')
    op.drop_table('gift_card_usos')
    op.drop_index(op.f('ix_sync_logs_integracion_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_table('rfid_scan_sessions')
    op.drop_index(op.f('ix_rfid_readers_reader_id'), table_name='rfid_readers')
    op.drop_table('rfid_readers')
    op.drop_index(op.f('ix_promocion_usos_promocion_id'), table_name='promocion_usos')
    op.drop_index(op.f('ix_promocion_usos_cliente_id'), table_name='promocion_usos')
    op.drop_table('promocion_usos')
    op.drop_index(op.f('ix_ordenes_omnicanal_tienda_id'), table_name='ordenes_omnicanal')
    op.drop_index(op.f('ix_ordenes_omnicanal_numero_orden'), table_name='ordenes_omnicanal')
    op.drop_index(op.f('ix_ordenes_omnicanal_fulfillment_status'), table_name='ordenes_omnicanal')
    op.drop_index(op.f('ix_ordenes_omnicanal_canal'), table_name='ordenes_omnicanal')
    op.drop_table('ordenes_omnicanal')
    op.drop_table('location_capabilities')
    op.drop_index(op.f('ix_gift_cards_codigo'), table_name='gift_cards')
    op.drop_table('gift_cards')
    op.drop_index(op.f('ix_customer_wallets_tienda_id'), table_name='customer_wallets')
    op.drop_index(op.f('ix_customer_wallets_cliente_id'), table_name='customer_wallets')
    op.drop_table('customer_wallets')
    op.drop_table('shipping_zones')
    op.drop_index(op.f('ix_promociones_tienda_id'), table_name='promociones')
    op.drop_index(op.f('ix_promociones_codigo_promocional'), table_name='promociones')
    op.drop_table('promociones')
    op.drop_table('loyalty_programs')
    op.drop_index(op.f('ix_integraciones_ecommerce_tienda_id'), table_name='integraciones_ecommerce')
    op.drop_table('integraciones_ecommerce')
    op.drop_index(op.f('ix_api_keys_tienda_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
