"""Initial migration - Create all tables

Revision ID: e216122cf21f
Revises: 
Create Date: 2025-11-26 23:30:28.002754

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e216122cf21f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rubro', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiendas_id'), 'tiendas', ['id'], unique=False)
    op.create_index(op.f('ix_tiendas_is_active'), 'tiendas', ['is_active'], unique=False)
    op.create_index(op.f('ix_tiendas_nombre'), 'tiendas', ['nombre'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('documento_tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('documento_numero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento_numero'), 'clientes', ['documento_numero'], unique=False)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_is_active'), 'clientes', ['is_active'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_tienda_id'), 'clientes', ['tienda_id'], unique=False)
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hex_code', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_tienda_id'), 'colors', ['tienda_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel_urgencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_is_active'), 'insights', ['is_active'], unique=False)
    op.create_index(op.f('ix_insights_nivel_urgencia'), 'insights', ['nivel_urgencia'], unique=False)
    op.create_index(op.f('ix_insights_tienda_id'), 'insights', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_insights_tipo'), 'insights', ['tipo'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('external_erp_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_tienda_id'), 'locations', ['tienda_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('precio_costo', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_is_active'), 'productos', ['is_active'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=False)
    op.create_index(op.f('ix_productos_tienda_id'), 'productos', ['tienda_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('base_sku', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_base_sku'), 'products', ['base_sku'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_tienda_id'), 'products', ['tienda_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cuit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_cuit'), 'proveedores', ['cuit'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_is_active'), 'proveedores', ['is_active'], unique=False)
    op.create_index(op.f('ix_proveedores_razon_social'), 'proveedores', ['razon_social'], unique=False)
    op.create_index(op.f('ix_proveedores_tienda_id'), 'proveedores', ['tienda_id'], unique=False)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_tienda_id'), 'sizes', ['tienda_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_tienda_id'), 'users', ['tienda_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('afip_cae', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('afip_cae_vto', sa.DateTime(), nullable=True),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_index(op.f('ix_ventas_payment_id'), 'ventas', ['payment_id'], unique=False)
    op.create_index(op.f('ix_ventas_status_pago'), 'ventas', ['status_pago'], unique=False)
    op.create_index(op.f('ix_ventas_tienda_id'), 'ventas', ['tienda_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_rol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payload_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_sensitive', 'audit_logs', ['action', 'is_sensitive'], unique=False)
    op.create_index('idx_audit_payload_after', 'audit_logs', ['payload_after'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_payload_before', 'audit_logs', ['payload_before'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_tienda_timestamp', 'audit_logs', ['tienda_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tienda_id'), 'audit_logs', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_venta_id'), 'detalles_venta', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_producto_id'), 'detalles_venta', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_venta_id'), 'detalles_venta', ['venta_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_factura', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero_comprobante', sa.Integer(), nullable=False),
    sa.Column('cae', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vencimiento_cae', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cliente_doc_tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cliente_doc_nro', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('monto_neto', sa.Float(), nullable=False),
    sa.Column('monto_iva', sa.Float(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('url_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_cae'), 'facturas', ['cae'], unique=False)
    op.create_index(op.f('ix_facturas_cliente_doc_nro'), 'facturas', ['cliente_doc_nro'], unique=False)
    op.create_index(op.f('ix_facturas_fecha_emision'), 'facturas', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_index(op.f('ix_facturas_numero_comprobante'), 'facturas', ['numero_comprobante'], unique=False)
    op.create_index(op.f('ix_facturas_punto_venta'), 'facturas', ['punto_venta'], unique=False)
    op.create_index(op.f('ix_facturas_tienda_id'), 'facturas', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_facturas_tipo_factura'), 'facturas', ['tipo_factura'], unique=False)
    op.create_index(op.f('ix_facturas_venta_id'), 'facturas', ['venta_id'], unique=True)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_compra_estado'), 'ordenes_compra', ['estado'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_fecha_emision'), 'ordenes_compra', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_id'), 'ordenes_compra', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_proveedor_id'), 'ordenes_compra', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_tienda_id'), 'ordenes_compra', ['tienda_id'], unique=False)
    op.create_table('permission_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permission_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_audits_tienda_id'), 'permission_audits', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_permission_audits_user_id'), 'permission_audits', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_index(op.f('ix_product_variants_tienda_id'), 'product_variants', ['tienda_id'], unique=False)
    op.create_table('sesiones_caja',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monto_inicial', sa.Float(), nullable=False),
    sa.Column('monto_final', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_caja_estado'), 'sesiones_caja', ['estado'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_fecha_apertura'), 'sesiones_caja', ['fecha_apertura'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_fecha_cierre'), 'sesiones_caja', ['fecha_cierre'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_id'), 'sesiones_caja', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_tienda_id'), 'sesiones_caja', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_usuario_id'), 'sesiones_caja', ['usuario_id'], unique=False)
    op.create_table('detalles_orden',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_costo_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('orden_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_orden_id'), 'detalles_orden', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_orden_orden_id'), 'detalles_orden', ['orden_id'], unique=False)
    op.create_index(op.f('ix_detalles_orden_producto_id'), 'detalles_orden', ['producto_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_doc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_inventory_ledger_location_id'), 'inventory_ledger', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_occurred_at'), 'inventory_ledger', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_tienda_id'), 'inventory_ledger', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_transaction_type'), 'inventory_ledger', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_variant_id'), 'inventory_ledger', ['variant_id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sesion_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_caja.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_created_at'), 'movimientos_caja', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_sesion_id'), 'movimientos_caja', ['sesion_id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_tienda_id'), 'movimientos_caja', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_tipo'), 'movimientos_caja', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_tipo'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_tienda_id'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_sesion_id'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_created_at'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_inventory_ledger_variant_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_transaction_type'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_tienda_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_occurred_at'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_location_id'), table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_detalles_orden_producto_id'), table_name='detalles_orden')
    op.drop_index(op.f('ix_detalles_orden_orden_id'), table_name='detalles_orden')
    op.drop_index(op.f('ix_detalles_orden_id'), table_name='detalles_orden')
    op.drop_table('detalles_orden')
    op.drop_index(op.f('ix_sesiones_caja_usuario_id'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_tienda_id'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_id'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_fecha_cierre'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_fecha_apertura'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_estado'), table_name='sesiones_caja')
    op.drop_table('sesiones_caja')
    op.drop_index(op.f('ix_product_variants_tienda_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_permission_audits_user_id'), table_name='permission_audits')
    op.drop_index(op.f('ix_permission_audits_tienda_id'), table_name='permission_audits')
    op.drop_table('permission_audits')
    op.drop_index(op.f('ix_ordenes_compra_tienda_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_proveedor_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_fecha_emision'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_estado'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_facturas_venta_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_tipo_factura'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_tienda_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_punto_venta'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_numero_comprobante'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_fecha_emision'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cliente_doc_nro'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cae'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_detalles_venta_venta_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_producto_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_id'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tienda_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_tienda_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_payload_before', table_name='audit_logs', postgresql_using='gin')
    op.drop_index('idx_audit_payload_after', table_name='audit_logs', postgresql_using='gin')
    op.drop_index('idx_audit_action_sensitive', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ventas_tienda_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_status_pago'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_payment_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_users_tienda_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sizes_tienda_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_proveedores_tienda_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_razon_social'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_is_active'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_cuit'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_products_tienda_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_base_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_productos_tienda_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_is_active'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_locations_tienda_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_insights_tipo'), table_name='insights')
    op.drop_index(op.f('ix_insights_tienda_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_nivel_urgencia'), table_name='insights')
    op.drop_index(op.f('ix_insights_is_active'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_colors_tienda_id'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_clientes_tienda_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_is_active'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento_numero'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_tiendas_nombre'), table_name='tiendas')
    op.drop_index(op.f('ix_tiendas_is_active'), table_name='tiendas')
    op.drop_index(op.f('ix_tiendas_id'), table_name='tiendas')
    op.drop_table('tiendas')
    # ### end Alembic commands ###
